name: app-build-action
#æ¨é€Tagæ—¶è§¦å‘
on:
  push:
    tags:
      - "*"
jobs:
  # MACOS é•œåƒ
  build-mac-ios-android:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # 1.1 ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v3
        with:
          ref: main
      # 1.2 å†™å‡ºç›¸å…³ç­¾å
      - name: Get Android Keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      # 1.2 è®¾ç½®JAVAç¯å¢ƒ
      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: "gradle"
      # 1.3 è®¾ç½®Flutterç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          cache: true
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop
      # 1.4 æ›´æ–°Flutterçš„packages
      - name: Restore Packages
        run: flutter pub get
      # 1.5 å®‰è£…appdmg npm install -g appdmg
      - name: Install appdmg
        run: npm install -g appdmg
      # 1.6 è®¾ç½®flutter_distributorç¯å¢ƒ
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
      # 1.7 build APK
      - name: Build APK
        run: flutter build apk --release
      # 1.8 build IOS
      - name: Build IPA
        run: flutter build ios --release --no-codesign
      # 1.9 åˆ›å»ºä¸€ä¸ªæœªç­¾åIPA
      - name: Create IPA
        run: |
          mkdir build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload
          cd ../../..
      # 1.10 build MAC ZIP\DMG
      - name: Build MacOS
        run: flutter_distributor package --platform macos --targets dmg,zip --skip-clean
      # 1.11 ä¸Šä¼ APK\IPA\MAC DMG\ZIP
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: document/RELEASE.txt
          token: ${{secrets.TOKEN }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/ios_no_sign.ipa
            build/dist/*/*.dmg
            build/dist/*/*.zip
        #å®Œæˆ
      - run: echo "ğŸ MacOS job's status is ${{ job.status }}."
  # Linux é•œåƒ
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 2.1 ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v3
        with:
          ref: main
      # 2.2 è®¾ç½®Flutterç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          cache: true
      - name: Install Dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Enable Flutter Desktop
        run: flutter config --enable-linux-desktop
      - name: Restore Packages
        run: flutter pub get
      # 2.3 è®¾ç½®flutter_distributorç¯å¢ƒ
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
      # 2.4 build Linux ZIP\DMG
      - name: Build Linux
        run: flutter_distributor package --platform linux --targets deb,zip --skip-clean
      # 2.5 ä¸Šä¼ ZIP\DMG
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: document/RELEASE.txt
          token: ${{secrets.TOKEN }}
          files: |
            build/dist/*/*.deb
            build/dist/*/*.zip
        #å®Œæˆ
      - run: echo "ğŸ Linux job's status is ${{ job.status }}."
  # Windows é•œåƒ
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # 3.1 ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v3
        with:
          ref: main
      # 3.2 è®¾ç½®Flutterç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          cache: true
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop
      - name: Restore Packages
        run: flutter pub get
      # 3.3 è®¾ç½®flutter_distributorç¯å¢ƒ
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
      # 3.4 build Windows ZIP\MSIX
      - name: Build Windows
        run: flutter_distributor package --platform windows --targets msix,zip --skip-clean
      # 3.5 ä¸Šä¼ ZIP\MSIX
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: document/RELEASE.txt
          token: ${{secrets.TOKEN }}
          files: |
            build/dist/*/*.msix
            build/dist/*/*.zip
        #å®Œæˆ
      - run: echo "ğŸ Windows job's status is ${{ job.status }}."
